### ISSUE TITLE
抖音网页版server.js再次调用出错

### ISSUE THREAD

**Issue by georgeJzzz** [yangshimin/SpiderCollection#2]
你好， 

最近也在研究抖音网页版，刚出douyin.com，研究了一个版本，现在已经失效了，返回数据为空。/(⊙﹏⊙)

看到你的项目，参考使用了下您的抖音网页版，现在遇到问题是，`第一次调用能成功，再次调用server.js状态码是500`，返回的`报错如下`:

![image](https://user-images.githubusercontent.com/42543889/134612578-b6edfc17-dbde-4186-8df3-17f2ab53038c.png)

望得到您的解惑

**Comment by yangshimin** [comment]
嗯  这个问题应该是第一次调用的时候js执行完毕没有退出 就保留了上下文环境 所以你第二次调用的时候就出问题了

**Comment by yangshimin** [comment]
> 你好，
> 
> 最近也在研究抖音网页版，刚出douyin.com，研究了一个版本，现在已经失效了，返回数据为空。/(⊙﹏⊙)
> 
> 看到你的项目，参考使用了下您的抖音网页版，现在遇到问题是，`第一次调用能成功，再次调用server.js状态码是500`，返回的`报错如下`:
> 
> ![image](https://user-images.githubusercontent.com/42543889/134612578-b6edfc17-dbde-4186-8df3-17f2ab53038c.png)
> 
> 望得到您的解惑

嗯 这个问题应该是第一次调用的时候js执行完毕没有退出 就保留了上下文环境 所以你第二次调用的时候就出问题了

**Comment by georgeJzzz** [comment]
收到。
![image](https://user-images.githubusercontent.com/42543889/135425768-f248dbd2-df77-420c-8e98-7c85d3d2b793.png)

刚操作了下，./douyin.html这块的请求以及注释了，应该没有上下文环境了。 

还是同样的问题，没有办法开启server.js后， 请求多次（第一次正常，第二次server.js报错）

**Comment by georgeJzzz** [comment]
是补环境那块有点异常， Proxy的代理导致吗。

希望再次得到你的解惑，感谢
